version: '3.8'

services:
  api:
    build: .
    container_name: language-api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - language-network

networks:
  language-network:
    driver: bridge